from io import BytesIO

from datetime import datetime
import os

print("REPORT FILE LOADED FROM:")
print(os.path.abspath(__file__))

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.database import SessionLocal
from app.services.analytics_service import get_analytics
from app.utils.auth import get_current_user

router = APIRouter()


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


@router.get("/download-report")
def download_report(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    print("******** NEW REPORT ROUTE EXECUTED ********")

    analytics = get_analytics(db)

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER
    title.textColor = colors.HexColor("#0B4F8C")

    heading = styles["Heading2"]
    heading.textColor = colors.HexColor("#0B4F8C")

    normal = styles["BodyText"]

    story = []

    story.append(
        Paragraph(
            "NetShield AI<br/>Network Security Report",
            title,
        )
    )

    story.append(Spacer(1, 0.30 * inch))

    story.append(
        Paragraph(
            f"<b>Generated By :</b> {current_user.full_name}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Email :</b> {current_user.email}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Date :</b> {datetime.now().strftime('%d %B %Y')}",
            normal,
        )
    )

    story.append(
        Paragraph(
            f"<b>Time :</b> {datetime.now().strftime('%I:%M:%S %p')}",
            normal,
        )
    )

    story.append(Spacer(1, 0.30 * inch))

    story.append(
        Paragraph(
            "Executive Summary",
            heading,
        )
    )

    summary = (
        "This report summarizes the network traffic monitored by "
        "NetShield AI and highlights detected anomalies using the "
        "machine learning intrusion detection system."
    )

    story.append(
        Paragraph(
            summary,
            normal,
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    story.append(
        Paragraph(
            "Threat Statistics",
            heading,
        )
    )

    average = round(
        analytics["average_confidence"] * 100,
        2,
    )

    stats = [
        ["Metric", "Value"],
        ["Total Predictions", analytics["total_predictions"]],
        ["High Confidence Threats", analytics["high_confidence"]],
        ["Average Confidence", f"{average}%"],
        ["Attack Categories", len(analytics["attack_distribution"])],
    ]

    table = Table(
        stats,
        colWidths=[250, 180],
    )

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0B4F8C")),
                ("TEXTCOLOR", (0,0), (-1,0), colors.white),
                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
                ("FONTSIZE", (0,0), (-1,0), 11),

                ("GRID", (0,0), (-1,-1), 0.5, colors.grey),

                ("BACKGROUND", (0,1), (-1,-1), colors.whitesmoke),

                ("ALIGN", (0,0), (-1,-1), "CENTER"),

                ("BOTTOMPADDING", (0,0), (-1,0), 10),
            ]
        )
    )

    story.append(table)

    story.append(Spacer(1, 0.30 * inch))

    story.append(
        Paragraph(
            "Attack Distribution",
            heading,
        )
    )

    attack_table = [
        [
            "Attack Type",
            "Occurrences",
        ]
    ]

    for attack in analytics["attack_distribution"]:

        attack_table.append(
            [
                attack["attack"],
                str(attack["count"]),
            ]
        )
    attackReport = Table(
        attack_table,
        colWidths=[300, 130],
    )

    attackReport.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#163A5F")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 11),

                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("ALIGN", (0, 0), (-1, -1), "CENTER"),

                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
            ]
        )
    )

    story.append(attackReport)

    story.append(Spacer(1, 0.35 * inch))

    story.append(
        Paragraph(
            "Risk Assessment",
            heading,
        )
    )

    if analytics["high_confidence"] == 0:
        risk = "LOW"
    elif analytics["high_confidence"] < 10:
        risk = "MEDIUM"
    else:
        risk = "HIGH"

    story.append(
        Paragraph(
            f"<b>Current Network Risk Level :</b> {risk}",
            normal,
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    story.append(
        Paragraph(
            "Security Recommendations",
            heading,
        )
    )

    recommendations = [
        "• Continuously monitor network traffic.",
        "• Investigate high-confidence detections immediately.",
        "• Keep IDS signatures and AI models updated.",
        "• Enable firewall and endpoint protection.",
        "• Regularly review security reports and logs.",
    ]

    for item in recommendations:
        story.append(
            Paragraph(
                item,
                normal,
            )
        )

    story.append(Spacer(1, 0.40 * inch))

    story.append(
        Paragraph(
            "<font color='#666666'><i>"
            "This report was automatically generated by "
            "NetShield AI Intrusion Detection System."
            "</i></font>",
            normal,
        )
    )
    print("Number of story elements:", len(story))
    doc.build(story)
    

    buffer.seek(0)

    filename = (
        "NetShield"
        + datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        + ".pdf"
    )

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        },
    )