import React, { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";

function ThreatReport() {

    const [report, setReport] = useState(null);

    useEffect(() => {

        const fetchReport = () => {

            axios.get("http://127.0.0.1:8000/traffic/threat-report")
            .then((res) => {
                setReport(res.data);
            });

        };

        fetchReport();

        const interval = setInterval(fetchReport, 5000);

        return () => clearInterval(interval);

    }, []);
const downloadPDF = () => {

    const doc = new jsPDF();

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(41, 98, 255);
    doc.text("NetShield AI", 20, 20);

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Threat Intelligence Report", 20, 30);

    doc.setDrawColor(41, 98, 255);
    doc.line(20, 35, 190, 35);

    // Summary
    doc.setFontSize(11);

    doc.text(`Generated At: ${report.generated_at}`, 20, 50);
    doc.text(`Total Packets: ${report.total_packets}`, 20, 60);
    doc.text(`Normal Traffic: ${report.normal_traffic}`, 20, 70);
    doc.text(`Attacks Detected: ${report.attacks_detected}`, 20, 80);
    doc.text(`Detection Rate: ${report.detection_rate}%`, 20, 90);

    // Protocols
    let y = 110;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Protocol Distribution", 20, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    Object.entries(report.protocols).forEach(([protocol, count]) => {
        doc.text(`${protocol}: ${count}`, 25, y);
        y += 8;
    });

    // Risks
    y += 5;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Risk Distribution", 20, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    Object.entries(report.risks).forEach(([risk, count]) => {
        doc.text(`${risk}: ${count}`, 25, y);
        y += 8;
    });

    // Top Threat
    y += 5;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Top Threat", 20, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(report.top_threat, 25, y);

    // Recommendation
    y += 15;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Recommendation", 20, y);

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const lines = doc.splitTextToSize(
        report.recommendation,
        170
    );

    doc.text(lines, 20, y);

    // Footer
    doc.setFontSize(10);
    doc.text("Generated by NetShield AI", 20, 285);

    doc.save("NetShield_AI_Threat_Report.pdf");
};
    if (!report) return <h2>Loading...</h2>;

    return (

        <div className="dashboard">

            <Sidebar />

            <div className="content">

                <Navbar />

                <h2>Threat Intelligence Report</h2>

                <div
                    style={{
                        background: "#fff",
                        padding: "20px",
                        borderRadius: "12px",
                        boxShadow: "0 2px 10px rgba(0,0,0,.1)"
                    }}
                >

                    <h3>Report Summary</h3>

                    <p><b>Generated At:</b> {report.generated_at}</p>
                    <p><b>Total Packets:</b> {report.total_packets}</p>
                    <p><b>Normal Traffic:</b> {report.normal_traffic}</p>
                    <p><b>Attacks Detected:</b> {report.attacks_detected}</p>
                    <p><b>Detection Rate:</b> {report.detection_rate}%</p>

                    <hr />

                    <h3>Protocol Distribution</h3>

                    {Object.entries(report.protocols).map(([key, value]) => (
                        <p key={key}>
                            {key}: {value}
                        </p>
                    ))}

                    <hr />

                    <h3>Risk Distribution</h3>

                    {Object.entries(report.risks).map(([key, value]) => (
                        <p key={key}>
                            {key}: {value}
                        </p>
                    ))}

                    <hr />

                    <h3>Top Threat</h3>

                    <p>{report.top_threat}</p>

                    <h3>Recommendation</h3>

                    <p>{report.recommendation}</p>

                    <button
    onClick={downloadPDF}
    style={{
        marginTop: "20px",
        padding: "12px 24px",
        background: "#2962FF",
        color: "#fff",
        border: "none",
        borderRadius: "8px",
        cursor: "pointer",
        fontWeight: "bold"
    }}
>
    Download PDF Report
</button>

                </div>

            </div>

        </div>

    );

}

export default ThreatReport;