import React, { useEffect, useState } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";
import "../styles/Dashboard.css";

function ThreatReport() {

    const [report, setReport] = useState(null);

    useEffect(() => {

        const fetchReport = () => {

            axios
                .get("http://127.0.0.1:8000/traffic/threat-report")
                .then((res) => {
                    setReport(res.data);
                })
                .catch((err) => {
                    console.error("Threat report error:", err);
                });

        };

        fetchReport();

        const interval = setInterval(fetchReport, 5000);

        return () => clearInterval(interval);

    }, []);


    // =========================================================
    // DOWNLOAD PDF
    // =========================================================

    const downloadPDF = () => {

        if (!report) return;

        const doc = new jsPDF();

        doc.setFont("helvetica", "bold");
        doc.setFontSize(22);
        doc.setTextColor(79, 70, 229);
        doc.text("NetShield AI", 20, 20);

        doc.setFontSize(16);
        doc.setTextColor(30, 41, 59);
        doc.text("Threat Intelligence Report", 20, 30);

        doc.setDrawColor(129, 140, 248);
        doc.line(20, 35, 190, 35);

        doc.setFontSize(11);

        doc.text(
            `Generated At: ${report.generated_at || "N/A"}`,
            20,
            50
        );

        doc.text(
            `Total Packets: ${report.total_packets}`,
            20,
            60
        );

        doc.text(
            `Normal Traffic: ${report.normal_traffic}`,
            20,
            70
        );

        doc.text(
            `Attacks Detected: ${report.attacks_detected}`,
            20,
            80
        );

        doc.text(
            `Detection Rate: ${report.detection_rate}%`,
            20,
            90
        );


        // Protocols

        let y = 110;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text("Protocol Distribution", 20, y);

        y += 10;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);

        Object.entries(report.protocols || {}).forEach(
            ([protocol, count]) => {

                doc.text(
                    `${protocol}: ${count}`,
                    25,
                    y
                );

                y += 8;
            }
        );


        // Risks

        y += 5;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text("Risk Distribution", 20, y);

        y += 10;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);

        Object.entries(report.risks || {}).forEach(
            ([risk, count]) => {

                doc.text(
                    `${risk}: ${count}`,
                    25,
                    y
                );

                y += 8;
            }
        );


        // Top Threat

        y += 5;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text("Top Threat", 20, y);

        y += 10;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);

        doc.text(
            report.top_threat || "None",
            25,
            y
        );


        // Recommendation

        y += 15;

        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text("Recommendation", 20, y);

        y += 10;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);

        const lines = doc.splitTextToSize(
            report.recommendation || "",
            170
        );

        doc.text(lines, 20, y);


        // Footer

        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);

        doc.text(
            "Generated by NetShield AI",
            20,
            285
        );

        doc.save(
            "NetShield_AI_Threat_Report.pdf"
        );
    };


    if (!report) {

        return (

            <div className="dashboard">

                <Sidebar />

                <div className="content">

                    <Navbar />

                    <div
                        style={{
                            padding: "40px",
                            textAlign: "center",
                            color: "#64748b"
                        }}
                    >
                        Loading Threat Report...
                    </div>

                </div>

            </div>

        );
    }


    // =========================================================
    // DATA
    // =========================================================

    const totalPackets =
        report.total_packets || 0;

    const normalTraffic =
        report.normal_traffic || 0;

    const attacksDetected =
        report.attacks_detected || 0;

    const detectionRate =
        report.detection_rate || 0;

    const protocols =
        report.protocols || {};

    const risks =
        report.risks || {};

    const topThreat =
        report.top_threat || "None";


    return (

        <div className="dashboard">

            <Sidebar />

            <div className="content">

                <Navbar />


                {/* =================================================
                    PAGE HEADER
                ================================================= */}

                <div
                    style={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                        marginBottom: "25px",
                        gap: "20px"
                    }}
                >

                    <div>

                        <h2
                            style={{
                                marginBottom: "5px",
                                color: "#1e3a8a",
                                fontSize: "28px"
                            }}
                        >
                            🛡️ Threat Intelligence Report
                        </h2>

                        <p
                            style={{
                                margin: 0,
                                color: "#64748b"
                            }}
                        >
                            Real-time analysis of detected network
                            threats and traffic activity.
                        </p>

                    </div>


                    <button
                        onClick={downloadPDF}
                        style={{
                            background: "#e0e7ff",
                            color: "#4338ca",
                            border: "1px solid #c7d2fe",
                            padding: "12px 20px",
                            borderRadius: "12px",
                            cursor: "pointer",
                            fontWeight: "700",
                            fontSize: "14px"
                        }}
                    >
                        📄 Download PDF
                    </button>

                </div>


                {/* =================================================
                    SUMMARY CARDS
                ================================================= */}

                <div
                    style={{
                        display: "grid",
                        gridTemplateColumns:
                            "repeat(4, minmax(180px, 1fr))",
                        gap: "20px",
                        marginBottom: "25px"
                    }}
                >

                    {/* TOTAL */}

                    <div
                        style={{
                            background: "#eef2ff",
                            border: "1px solid #dbeafe",
                            borderRadius: "18px",
                            padding: "22px",
                            borderBottom:
                                "4px solid #6366f1"
                        }}
                    >

                        <div
                            style={{
                                fontSize: "25px",
                                marginBottom: "8px"
                            }}
                        >
                            📊
                        </div>

                        <div
                            style={{
                                color: "#4f46e5",
                                fontWeight: "600"
                            }}
                        >
                            Total Packets
                        </div>

                        <div
                            style={{
                                fontSize: "32px",
                                fontWeight: "800",
                                color: "#4338ca",
                                marginTop: "5px"
                            }}
                        >
                            {totalPackets}
                        </div>

                    </div>


                    {/* NORMAL */}

                    <div
                        style={{
                            background: "#ecfdf5",
                            border: "1px solid #d1fae5",
                            borderRadius: "18px",
                            padding: "22px",
                            borderBottom:
                                "4px solid #10b981"
                        }}
                    >

                        <div
                            style={{
                                fontSize: "25px",
                                marginBottom: "8px"
                            }}
                        >
                            🛡️
                        </div>

                        <div
                            style={{
                                color: "#059669",
                                fontWeight: "600"
                            }}
                        >
                            Normal Traffic
                        </div>

                        <div
                            style={{
                                fontSize: "32px",
                                fontWeight: "800",
                                color: "#059669",
                                marginTop: "5px"
                            }}
                        >
                            {normalTraffic}
                        </div>

                    </div>


                    {/* ATTACKS */}

                    <div
                        style={{
                            background: "#fff1f2",
                            border: "1px solid #ffe4e6",
                            borderRadius: "18px",
                            padding: "22px",
                            borderBottom:
                                "4px solid #f43f5e"
                        }}
                    >

                        <div
                            style={{
                                fontSize: "25px",
                                marginBottom: "8px"
                            }}
                        >
                            🚨
                        </div>

                        <div
                            style={{
                                color: "#e11d48",
                                fontWeight: "600"
                            }}
                        >
                            Attacks Detected
                        </div>

                        <div
                            style={{
                                fontSize: "32px",
                                fontWeight: "800",
                                color: "#e11d48",
                                marginTop: "5px"
                            }}
                        >
                            {attacksDetected}
                        </div>

                    </div>


                    {/* DETECTION RATE */}

                    <div
                        style={{
                            background: "#fff7ed",
                            border: "1px solid #fed7aa",
                            borderRadius: "18px",
                            padding: "22px",
                            borderBottom:
                                "4px solid #f59e0b"
                        }}
                    >

                        <div
                            style={{
                                fontSize: "25px",
                                marginBottom: "8px"
                            }}
                        >
                            📈
                        </div>

                        <div
                            style={{
                                color: "#d97706",
                                fontWeight: "600"
                            }}
                        >
                            Detection Rate
                        </div>

                        <div
                            style={{
                                fontSize: "32px",
                                fontWeight: "800",
                                color: "#d97706",
                                marginTop: "5px"
                            }}
                        >
                            {detectionRate}%
                        </div>

                    </div>

                </div>


                {/* =================================================
                    TOP THREAT
                ================================================= */}

                <div
                    style={{
                        background: "#fff1f2",
                        border: "1px solid #fecdd3",
                        borderRadius: "18px",
                        padding: "22px",
                        marginBottom: "25px"
                    }}
                >

                    <div
                        style={{
                            color: "#be123c",
                            fontWeight: "700",
                            fontSize: "18px",
                            marginBottom: "8px"
                        }}
                    >
                        🚨 Top Threat
                    </div>

                    <div
                        style={{
                            color: "#334155",
                            fontSize: "20px",
                            fontWeight: "700"
                        }}
                    >
                        {topThreat}
                    </div>

                </div>


                {/* =================================================
                    TWO COLUMN DISTRIBUTION
                ================================================= */}

                <div
                    style={{
                        display: "grid",
                        gridTemplateColumns:
                            "repeat(2, minmax(300px, 1fr))",
                        gap: "25px",
                        marginBottom: "25px"
                    }}
                >

                    {/* PROTOCOL */}

                    <div
                        style={{
                            background: "#ffffff",
                            borderRadius: "18px",
                            padding: "25px",
                            boxShadow:
                                "0 6px 20px rgba(99,102,241,0.08)"
                        }}
                    >

                        <h3
                            style={{
                                color: "#1e3a8a",
                                marginTop: 0
                            }}
                        >
                            🌐 Protocol Distribution
                        </h3>

                        {Object.entries(protocols).map(
                            ([key, value]) => (

                                <div
                                    key={key}
                                    style={{
                                        display: "flex",
                                        justifyContent:
                                            "space-between",
                                        alignItems: "center",
                                        padding: "12px 14px",
                                        marginBottom: "8px",
                                        background: "#f8fafc",
                                        borderRadius: "10px"
                                    }}
                                >

                                    <span
                                        style={{
                                            color: "#475569",
                                            fontWeight: "600"
                                        }}
                                    >
                                        {key}
                                    </span>

                                    <span
                                        style={{
                                            background: "#e0e7ff",
                                            color: "#4338ca",
                                            padding:
                                                "5px 12px",
                                            borderRadius:
                                                "20px",
                                            fontWeight: "700"
                                        }}
                                    >
                                        {value}
                                    </span>

                                </div>

                            )
                        )}

                    </div>


                    {/* RISK */}

                    <div
                        style={{
                            background: "#ffffff",
                            borderRadius: "18px",
                            padding: "25px",
                            boxShadow:
                                "0 6px 20px rgba(99,102,241,0.08)"
                        }}
                    >

                        <h3
                            style={{
                                color: "#1e3a8a",
                                marginTop: 0
                            }}
                        >
                            ⚠️ Risk Distribution
                        </h3>

                        {Object.entries(risks).map(
                            ([key, value]) => {

                                let background =
                                    "#ecfdf5";

                                let color =
                                    "#059669";

                                if (
                                    key === "High"
                                ) {
                                    background =
                                        "#fff1f2";

                                    color =
                                        "#e11d48";
                                }

                                if (
                                    key === "Critical"
                                ) {
                                    background =
                                        "#ffe4e6";

                                    color =
                                        "#be123c";
                                }

                                if (
                                    key === "Medium"
                                ) {
                                    background =
                                        "#fff7ed";

                                    color =
                                        "#d97706";
                                }

                                return (

                                    <div
                                        key={key}
                                        style={{
                                            display: "flex",
                                            justifyContent:
                                                "space-between",
                                            alignItems:
                                                "center",
                                            padding:
                                                "12px 14px",
                                            marginBottom:
                                                "8px",
                                            background,
                                            borderRadius:
                                                "10px"
                                        }}
                                    >

                                        <span
                                            style={{
                                                color,
                                                fontWeight:
                                                    "600"
                                            }}
                                        >
                                            {key}
                                        </span>

                                        <span
                                            style={{
                                                color,
                                                fontWeight:
                                                    "800",
                                                fontSize:
                                                    "17px"
                                            }}
                                        >
                                            {value}
                                        </span>

                                    </div>

                                );

                            }
                        )}

                    </div>

                </div>


                {/* =================================================
                    RECOMMENDATION
                ================================================= */}

                <div
                    style={{
                        background: "#eff6ff",
                        border: "1px solid #dbeafe",
                        borderRadius: "18px",
                        padding: "25px",
                        marginBottom: "30px"
                    }}
                >

                    <h3
                        style={{
                            marginTop: 0,
                            color: "#1d4ed8"
                        }}
                    >
                        💡 Security Recommendation
                    </h3>

                    <p
                        style={{
                            color: "#475569",
                            lineHeight: "1.7",
                            marginBottom: 0
                        }}
                    >
                        {report.recommendation}
                    </p>

                </div>


                {/* =================================================
                    REPORT INFORMATION
                ================================================= */}

                <div
                    style={{
                        textAlign: "center",
                        color: "#94a3b8",
                        fontSize: "13px",
                        paddingBottom: "25px"
                    }}
                >

                    Last updated:{" "}
                    {report.generated_at || "N/A"}

                    <br />

                    NetShield AI • Threat Intelligence

                </div>

            </div>

        </div>

    );

}

export default ThreatReport;